version: '3.7'
services:
  # https://github.com/qownnotes/docker-desktop
  desktop:
    image: pbeke/qownnotes-docker-desktop
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
      - desktop-home:/home
    environment:
      - USER=demo
      - PASSWORD=demo
      - TZ=Europe/Vienna
    ports:
      - 6080:80

volumes:
  desktop-home:
