version: '3.7'
services:
  # https://github.com/qownnotes/docker-desktop
  desktop:
    image: pbeke/qownnotes-docker-desktop
    restart: unless-stopped
    environment:
      - TZ=Europe/Vienna
    ports:
      - 6080:80

  # https://github.com/qownnotes/docker-nextbackup
  nextcloud:
    image: pbeke/qownnotes-docker-nextcloud
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=mydb
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud
      - TZ=Europe/Vienna
